### ISSUE TITLE
Menú no disponible 

### ISSUE THREAD

**Issue by imorlxs** [alejandrocq/ComedoresUGRbot#4]
Esta semana al intentar ver el menú de hoy jueves 3 de noviembre dice que no está disponible, cuando si lo está.

**Comment by alejandrocq** [comment]
Hola @imorlxs !

Muchas gracias por el aviso. Ya lo he solucionado en el commit https://github.com/alejandrocq/ComedoresUGRbot/commit/56ae1c9af0edd6eb5d528df70d04c5b785deb8bd

Saludos.
