### ISSUE TITLE
Mantenimiento al bot de comedores UGR

### ISSUE THREAD

**Issue by RestlessWolf** [alejandrocq/ComedoresUGRbot#5]
Hola! primero de todo, gracias por el bot, nos haces la vida un pelín más fácil <3.

Segundo; creo que actualizaron la página de comedores y el bot no es capaz de decirte qué hay de comer día a día ( /lunes,/martes..../sábado no funcionan y /hoy tampoco), pero sí es capaz de generar el pdf de la semana completa. Creo que quitaron los menús de la página principal, que debía ser donde estaban, y ahora solo aparecen en este enlace: https://scu.ugr.es/pages/menu 

Entendería que no te apeteciese arreglarlo, solo quería comentar el problema, gracias de antemano c:

**Comment by alejandrocq** [comment]
Hola,

Muchísimas gracias por el aviso. Tengo que ponerme alguna alerta para esto, pero no le he dedicado tiempo. De vez en cuando cambian algo que me rompe el renderizado de las imágenes, pero bueno en este caso ha sido solo un cambio en la URL.

Me alegra que os sirva y por favor, avisadme de cualquier problema y le echo un vistazo en cuando tenga tiempo. También se admiten mejoras si alguien se anima 😉 

Ya está arreglado en https://github.com/alejandrocq/ComedoresUGRbot/commit/7c97278997906277e6a8965433e811318d1b1281

Saludos.
